{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cswx-pc.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  namespace: {{ include "cswx-pc.namespace" . }}
  name: {{ $fullName }}
  labels:
    {{- include "cswx-pc.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    nginx.org/websocket-services: "{{ $fullName }}"
    nginx.org/websocket-services: "ws-svc"
    nginx.org/server-snippets: |
      location ^~ /api/ {
        proxy_pass http://api-test.yunxuebao.com/;
        
      }
      location ^~ /yunxuebao/test/ {
            proxy_pass http://oss-image.yunxuebao.com;
      }
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
