{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "cswx-pc.namespace" . }}
  name: {{ include "cswx-pc.serviceAccountName" . }}
  labels:
{{ include "cswx-pc.labels" . | nindent 4 }}
{{- end -}}
