# 拉取基础镜像
FROM registry.cn-shanghai.aliyuncs.com/base-service/base-image:web-nginx
#作者
MAINTAINER keray

# 指定运行时的系统环境变量,如下请替换appName为自己应用名称
ARG APP_NAME
ARG ENV
# 创建文件夹
RUN mkdir -p  /home/admin/bin/
RUN mkdir -p  /var/logs
RUN mkdir -p  /var/log/nginx

# 将应用启动脚本配置复制到镜像中
# COPY ./ADDP-INF/nginx.conf /etc/nginx/nginx.conf
# 复制应用到镜像
COPY ./dist  /home/admin/dist

#定义程序默认端口
EXPOSE 3000

# 启动容器时进入的工作目录
WORKDIR /home/admin/

#容器启动时自动执行的脚本，我们一般会将应用启动脚本放在这里，相当于系统自启应用
STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
